### ISSUE TITLE
OpenSSL::Cipher::CipherError (iv length too short)

### ISSUE THREAD

**Issue by jaigouk** [chicks/devise_aes_encryptable#1]
Got an error while I'm trying to signup. It works with :bcrypt or :authlogic_sha512.

Started POST "/users/register" for 127.0.0.1 at 2011-01-12 18:16:10 +0900
  Processing by Devise::RegistrationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"f+paB/eEKbJLbvi9WTdhlaINRPNiyV0jZtRYF/1iUwM=", "user"=>{"username"=>"kuro7", "email"=>"", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}
Completed   in 1ms
OpenSSL::Cipher::CipherError (iv length too short):

my devisse configs are,

require 'devise/orm/mongoid'  
config.stretches = 20
config.encryptor = :aes256
config.pepper = "6f68ed4ea8.."

I downloaded  your github repo and ran the test. It was fine.

Could you help me with this?

**Comment by chicks** [comment]
Yeah, sorry about that.  I released this gem a little early - before it was really complete.  I'll try and get this fixed today.

**Comment by jaigouk** [comment]
awesome!

**Comment by chicks** [comment]
Hey, this is fixed.  You'll need to delete and recreate any users that you created on the previous version of this gem before it will work properly!
