### ISSUE TITLE
Error when deploying project through Amazon Opsworks

### ISSUE THREAD

**Issue by dzoltok** [chicks/devise_aes_encryptable#5]
With this line in our Gemfile:

```
gem 'devise_aes_encryptable', git: 'https://github.com/chicks/devise_aes_encryptable.git', branch: 'master'
```

Our team is running the following line as part of our deployments:

```
sudo su - deploy -c 'cd /srv/www/project/releases/current && /usr/local/bin/bundle install --path /home/deploy/.bundler/project --without=test development' 2>&1
```

And getting the following error:

```
SystemStackError: stack level too deep
An error occurred while installing devise_aes_encryptable (0.2.3), and Bundler cannot continue.
Make sure that `gem install devise_aes_encryptable -v '0.2.3'` succeeds before bundling.
```

Now, the master branch isn't v0.2.3, as it's been updated to be Rails 4 compatible, but OpsWorks looks like it's still trying to get the old version. I suspect it's being tripped up on the fact that the gem is coming from Github instead of the RubyGems repository. If no one else is willing or able to take over this project to push a new version, let me know and I will.

**Comment by aaroncraigongithub** [comment]
I know this is old, so you may have sorted it out already, but I'm getting the same issue, and it's due to the default Bundler version on Ops being fairly old.  If you ssh onto the machine and run `sudo gem update` and then run the bundle install, it will probably work.
